#include<stdio.h>
#include<conio.h>
void main()
{
int a,b,c,d,e;
clrscr();
printf("enter the value of a:");
scanf("%d",&a);
printf("enter the value of b:");
scanf("%d",&b);
printf("enter the value of c:");
scanf("%d",&c);
printf("enter the value of d:");
scanf("%d",&d);
printf("enter the value of e:");
scnaf("%d",&e);
if(a>b&&a>c&&a>d&&a>e)
{
	printf("a is the biggest number.");
}
else if(b>a&&b>c&&b>d&&b>e)
{
	printf("b is the biggest number.");
}
else if(c>a&&c>b&&c>)